# Generated by Django 5.0.6 on 2025-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('rejected', 'Rejected')], default='created', max_length=20),
        ),
    ]
